In [1]:
from bs4 import BeautifulSoup
import requests

url = BeautifulSoup('https://www.worldometers.info/coronavirus/', 'html.parser')
soup = requests.get(url)
soup

/usr/local/lib/python3.7/dist-packages/bs4/__init__.py:336: UserWarning: "https://www.worldometers.info/coronavirus/" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

In [2]:
soup = soup.text

In [4]:
soup = BeautifulSoup(soup, "lxml")
soup

TypeError: ignored

In [5]:
table = soup.table
table

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">TotÂ Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
<th width="30">New Cases/1M pop</th>
<th width="30">New Deaths/1M pop</th>
<th width="30">Active Cases/1M pop</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>103,143,208</td>
<td></td>
<td>1,479,512</td>
<td></td>
<td>97,000,537</td>
<td></td>
<td>4,663,159</td>
<td>8,179</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>158,842,694</td>
<td>+42,438</td>
<td>1,435,027</td>
<td>+32</td>
<td>152,797,714</td>
<td>+63,660</td>
<td>4,609,953</td>
<td>10,581</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>58,405,997</td>
<td></td>
<td>1,300,973</td>
<td></td>
<td>55,432,640</td>
<td></td>
<td>1,672,384</td>
<td>10,526</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>198,761,428</td>
<td></td>
<td>1,847,603</td>
<td></td>
<td>190,290,528</td>
<td>+34,430</td>
<td>6,623,297</td>
<td>5,758</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>9,185,805</td>
<td>+14,647</td>
<td>13,034</td>
<td>+12</td>
<td>8,842,533</td>
<td>+4,482</td>
<td>330,238</td>
<td>120</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>12,205,182</td>
<td></td>
<td>255,310</td>
<td></td>
<td>11,410,731</td>
<td></td>
<td>539,141</td>
<td>975</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>706</td>
<td></td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>540,545,035</td>
<td>+57,085</td>
<td>6,331,474</td>
<td>+44</td>
<td>515,775,389</td>
<td>+102,545</td>
<td>18,438,172</td>
<td>36,139</td>
<td>69,347</td>
<td>812.3</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">87,321,703</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">1,035,847 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">83,159,792</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">3,126,064</td>
<td style="font-weight: bold; text-align:right">2,812</td>
<td style="font-weight: bold; text-align:right">260,840</td>
<td style="font-weight: bold; text-align:right">3,094</td>
<td style="font-weight: bold; text-align:right">1,039,574,344</td>
<td style="font-weight: bold; text-align:right">3,105,329</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,771,130</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<td>4</td><td>323</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">9,338</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">43,232,004</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">524,761 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">42,652,743</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">54,500</td>
<td style="font-weight: bold; text-align:right">698</td>
<td style="font-weight: bold; text-align:right">30,741</td>
<td style="font-weight: bold; text-align:right">373</td>
<td style="font-weight: bold; text-align:right">854,859,461</td>
<td style="font-weight: bold; text-align:right">607,858</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,347,202</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>33</td><td>2,680</td><td>2</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">39</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">31,456,865</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">668,177 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">30,182,173</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">606,515</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">145,976</td>
<td style="font-weight: bold; text-align:right">3,101</td>
<td style="font-weight: bold; text-align:right">63,776,166</td>
<td style="font-weight: bold; text-align:right">295,955</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,493,041</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>7</td><td>323</td><td>3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,815</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">29,849,919</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">148,749 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">29,210,587</span></td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">490,583</td>
<td style="font-weight: bold; text-align:right">869</td>
<td style="font-weight: bold; text-align:right">455,349</td>
<td style="font-weight: bold; text-align:right">2,269</td>
<td style="font-weight: bold; text-align:right">271,490,188</td>
<td style="font-weight: bold; text-align:right">4,141,480</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,553,913</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>2</td><td>441</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">7,484</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">26,847,783</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">140,183 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">25,882,900</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">824,700</td>
<td style="font-weight: bold; text-align:right">631</td>
<td style="font-weight: bold; text-align:right">318,464</td>
<td style="font-weight: bold; text-align:right">1,663</td>
<td style="font-weight: bold; text-align:right">122,332,384</td>
<td style="font-weight: bold; text-align:right">1,451,085</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">84,304,052</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>3</td><td>601</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">9,782</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">22,382,352</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">179,217 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">22,037,192</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+9,380</td>
<td style="text-align:right;font-weight:bold;">165,943</td>
<td style="font-weight: bold; text-align:right">188</td>
<td style="font-weight: bold; text-align:right">326,376</td>
<td style="font-weight: bold; text-align:right">2,613</td>
<td style="font-weight: bold; text-align:right">522,526,476</td>
<td style="font-weight: bold; text-align:right">7,619,407</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,578,364</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>3</td><td>383</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,420</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">18,376,587</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">380,020 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">17,794,561</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">202,006</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">125,819</td>
<td style="font-weight: bold; text-align:right">2,602</td>
<td style="font-weight: bold; text-align:right">273,400,000</td>
<td style="font-weight: bold; text-align:right">1,871,886</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">146,055,938</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>8</td><td>384</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,383</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
<td style="font-weight: bold; text-align:right">18,229,288</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+3,828</td>
<td style="font-weight: bold; text-align:right;">24,388 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+17</td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">18,012,349</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+18,777</td>
<td style="text-align:right;font-weight:bold;">192,551</td>
<td style="font-weight: bold; text-align:right">95</td>
<td style="font-weight: bold; text-align:right">354,967</td>
<td style="font-weight: bold; text-align:right">475</td>
<td style="font-weight: bold; text-align:right">15,804,065</td>
<td style="font-weight: bold; text-align:right">307,742</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,354,840</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>3</td><td>2,106</td><td>3</td>
<td style="font-weight: bold; text-align:right">75</td>
<td style="font-weight: bold; text-align:right">0.3</td>
<td style="font-weight: bold; text-align:right">3,749</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">17,653,375</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">167,391 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">16,863,770</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">622,214</td>
<td style="font-weight: bold; text-align:right">183</td>
<td style="font-weight: bold; text-align:right">292,811</td>
<td style="font-weight: bold; text-align:right">2,776</td>
<td style="font-weight: bold; text-align:right">223,025,536</td>
<td style="font-weight: bold; text-align:right">3,699,259</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,289,249</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>3</td><td>360</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">10,320</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
<td style="font-weight: bold; text-align:right">15,072,747</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">98,965 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">14,971,256</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">2,526</td>
<td style="font-weight: bold; text-align:right">975</td>
<td style="font-weight: bold; text-align:right">175,059</td>
<td style="font-weight: bold; text-align:right">1,149</td>
<td style="font-weight: bold; text-align:right">162,743,369</td>
<td style="font-weight: bold; text-align:right">1,890,142</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">86,101,118</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>6</td><td>870</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">29</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
<td style="font-weight: bold; text-align:right">12,478,994</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">107,108 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">11,939,322</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">432,564</td>
<td style="font-weight: bold; text-align:right">339</td>
<td style="font-weight: bold; text-align:right">266,703</td>
<td style="font-weight: bold; text-align:right">2,289</td>
<td style="font-weight: bold; text-align:right">471,036,328</td>
<td style="font-weight: bold; text-align:right">10,067,044</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,789,933</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>4</td><td>437</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">9,245</td>
</tr>

In [6]:
tags = table.find_all('tr')
tags

[<tr>
 <th width="1%">#</th>
 <th width="100">Country,<br/>Other</th>
 <th width="20">Total<br/>Cases</th>
 <th width="30">New<br/>Cases</th>
 <th width="30">Total<br/>Deaths</th>
 <th width="30">New<br/>Deaths</th>
 <th width="30">Total<br/>Recovered</th>
 <th width="30">New<br/>Recovered</th>
 <th width="30">Active<br/>Cases</th>
 <th width="30">Serious,<br/>Critical</th>
 <th width="30">TotÂ Cases/<br/>1M pop</th>
 <th width="30">Deaths/<br/>1M pop</th>
 <th width="30">Total<br/>Tests</th>
 <th width="30">Tests/<br/>
 <nobr>1M pop</nobr>
 </th>
 <th width="30">Population</th>
 <th style="display:none" width="30">Continent</th>
 <th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
 <th width="30">New Cases/1M pop</th>
 <th width="30">New Deaths/1M pop</th>
 <th width="30">Active Cases/1M pop</th>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="North America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>North America</nobr>
 </td>
 <td>103,143,208</td>
 <td></td>
 <td>1,479,512</td>
 <td></td>
 <td>97,000,537</td>
 <td></td>
 <td>4,663,159</td>
 <td>8,179</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="North America" style="display:none;">North America</td>
 <td>
 </td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Asia</nobr>
 </td>
 <td>158,842,694</td>
 <td>+42,438</td>
 <td>1,435,027</td>
 <td>+32</td>
 <td>152,797,714</td>
 <td>+63,660</td>
 <td>4,609,953</td>
 <td>10,581</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Asia" style="display:none;">Asia</td>
 <td>
 </td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="South America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>South America</nobr>
 </td>
 <td>58,405,997</td>
 <td></td>
 <td>1,300,973</td>
 <td></td>
 <td>55,432,640</td>
 <td></td>
 <td>1,672,384</td>
 <td>10,526</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="South America" style="display:none;">South America</td>
 <td>
 </td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Europe</nobr>
 </td>
 <td>198,761,428</td>
 <td></td>
 <td>1,847,603</td>
 <td></td>
 <td>190,290,528</td>
 <td>+34,430</td>
 <td>6,623,297</td>
 <td>5,758</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Europe" style="display:none;">Europe</td>
 <td>
 </td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Oceania</nobr>
 </td>
 <td>9,185,805</td>
 <td>+14,647</td>
 <td>13,034</td>
 <td>+12</td>
 <td>8,842,533</td>
 <td>+4,482</td>
 <td>330,238</td>
 <td>120</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
 <td>
 </td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Africa</nobr>
 </td>
 <td>12,205,182</td>
 <td></td>
 <td>255,310</td>
 <td></td>
 <td>11,410,731</td>
 <td></td>
 <td>539,141</td>
 <td>975</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Africa" style="display:none;">Africa</td>
 <td>
 </td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr></nobr>
 </td>
 <td>721</td>
 <td></td>
 <td>15</td>
 <td></td>
 <td>706</td>
 <td></td>
 <td>0</td>
 <td>0</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="" style="display:none;"></td>
 <td>
 </td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world">
 <td></td>
 <td style="text-align:left;">World</td>
 <td>540,545,035</td>
 <td>+57,085</td>
 <td>6,331,474</td>
 <td>+44</td>
 <td>515,775,389</td>
 <td>+102,545</td>
 <td>18,438,172</td>
 <td>36,139</td>
 <td>69,347</td>
 <td>812.3</td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="all" style="display:none">All</td>
 <td>
 </td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
 <td style="font-weight: bold; text-align:right">87,321,703</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">1,035,847 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">83,159,792</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">3,126,064</td>
 <td style="font-weight: bold; text-align:right">2,812</td>
 <td style="font-weight: bold; text-align:right">260,840</td>
 <td style="font-weight: bold; text-align:right">3,094</td>
 <td style="font-weight: bold; text-align:right">1,039,574,344</td>
 <td style="font-weight: bold; text-align:right">3,105,329</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,771,130</a> </td>
 <td data-continent="North America" style="display:none">North America</td>
 <td>4</td><td>323</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">9,338</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
 <td style="font-weight: bold; text-align:right">43,232,004</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">524,761 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">42,652,743</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">54,500</td>
 <td style="font-weight: bold; text-align:right">698</td>
 <td style="font-weight: bold; text-align:right">30,741</td>
 <td style="font-weight: bold; text-align:right">373</td>
 <td style="font-weight: bold; text-align:right">854,859,461</td>
 <td style="font-weight: bold; text-align:right">607,858</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,347,202</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <td>33</td><td>2,680</td><td>2</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">39</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
 <td style="font-weight: bold; text-align:right">31,456,865</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">668,177 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">30,182,173</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">606,515</td>
 <td style="font-weight: bold; text-align:right">8,318</td>
 <td style="font-weight: bold; text-align:right">145,976</td>
 <td style="font-weight: bold; text-align:right">3,101</td>
 <td style="font-weight: bold; text-align:right">63,776,166</td>
 <td style="font-weight: bold; text-align:right">295,955</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,493,041</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <td>7</td><td>323</td><td>3</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">2,815</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
 <td style="font-weight: bold; text-align:right">29,849,919</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">148,749 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">29,210,587</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">490,583</td>
 <td style="font-weight: bold; text-align:right">869</td>
 <td style="font-weight: bold; text-align:right">455,349</td>
 <td style="font-weight: bold; text-align:right">2,269</td>
 <td style="font-weight: bold; text-align:right">271,490,188</td>
 <td style="font-weight: bold; text-align:right">4,141,480</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,553,913</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>2</td><td>441</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">7,484</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
 <td style="font-weight: bold; text-align:right">26,847,783</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">140,183 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">25,882,900</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">824,700</td>
 <td style="font-weight: bold; text-align:right">631</td>
 <td style="font-weight: bold; text-align:right">318,464</td>
 <td style="font-weight: bold; text-align:right">1,663</td>
 <td style="font-weight: bold; text-align:right">122,332,384</td>
 <td style="font-weight: bold; text-align:right">1,451,085</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">84,304,052</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>3</td><td>601</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">9,782</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
 <td style="font-weight: bold; text-align:right">22,382,352</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">179,217 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">22,037,192</span></td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+9,380</td>
 <td style="text-align:right;font-weight:bold;">165,943</td>
 <td style="font-weight: bold; text-align:right">188</td>
 <td style="font-weight: bold; text-align:right">326,376</td>
 <td style="font-weight: bold; text-align:right">2,613</td>
 <td style="font-weight: bold; text-align:right">522,526,476</td>
 <td style="font-weight: bold; text-align:right">7,619,407</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,578,364</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>3</td><td>383</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">2,420</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
 <td style="font-weight: bold; text-align:right">18,376,587</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">380,020 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">17,794,561</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">202,006</td>
 <td style="font-weight: bold; text-align:right">2,300</td>
 <td style="font-weight: bold; text-align:right">125,819</td>
 <td style="font-weight: bold; text-align:right">2,602</td>
 <td style="font-weight: bold; text-align:right">273,400,000</td>
 <td style="font-weight: bold; text-align:right">1,871,886</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">146,055,938</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>8</td><td>384</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">1,383</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
 <td style="font-weight: bold; text-align:right">18,229,288</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+3,828</td>
 <td style="font-weight: bold; text-align:right;">24,388 </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+17</td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">18,012,349</span></td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+18,777</td>
 <td style="text-align:right;font-weight:bold;">192,551</td>
 <td style="font-weight: bold; text-align:right">95</td>
 <td style="font-weight: bold; text-align:right">354,967</td>
 <td style="font-weight: bold; text-align:right">475</td>
 <td style="font-weight: bold; text-align:right">15,804,065</td>
 <td style="font-weight: bold; text-align:right">307,742</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,354,840</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <td>3</td><td>2,106</td><td>3</td>
 <td style="font-weight: bold; text-align:right">75</td>
 <td style="font-weight: bold; text-align:right">0.3</td>
 <td style="font-weight: bold; text-align:right">3,749</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
 <td style="font-weight: bold; text-align:right">17,653,375</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">167,391 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">16,863,770</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">622,214</td>
 <td style="font-weight: bold; text-align:right">183</td>
 <td style="font-weight: bold; text-align:right">292,811</td>
 <td style="font-weight: bold; text-align:right">2,776</td>
 <td style="font-weight: bold; text-align:right">223,025,536</td>
 <td style="font-weight: bold; text-align:right">3,699,259</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,289,249</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>3</td><td>360</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">10,320</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
 <td style="font-weight: bold; text-align:right">15,072,747</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">98,965 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">14,971,256</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">2,526</td>
 <td style="font-weight: bold; text-align:right">975</td>
 <td style="font-weight: bold; text-align:right">175,059</td>
 <td style="font-weight: bold; text-align:right">1,149</td>
 <td style="font-weight: bold; text-align:right">162,743,369</td>
 <td style="font-weight: bold; text-align:right">1,890,142</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">86,101,118</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <td>6</td><td>870</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">29</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
 <td style="font-weight: bold; text-align:right">12,478,994</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">107,108 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">11,939,322</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">432,564</td>
 <td style="font-weight: bold; text-align:right">339</td>
 <td style="font-weight: bold; text-align:right">266,703</td>
 <td style="font-weight: bold; text-align:right">2,289</td>
 <td style="font-weight: bold; text-align:right">471,036,328</td>
 <td style="font-weight: bold; text-align:right">10,067,044</td>

In [10]:
data = []
for tag in tags:
  x = tag.text
  x = x.split('\n')
  data.append(x[1:-1])

print(data)

[['#', 'Country,Other', 'TotalCases', 'NewCases', 'TotalDeaths', 'NewDeaths', 'TotalRecovered', 'NewRecovered', 'ActiveCases', 'Serious,Critical', 'Tot\xa0Cases/1M pop', 'Deaths/1M pop', 'TotalTests', 'Tests/', '1M pop', '', 'Population', 'Continent', '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl', 'New Cases/1M pop', 'New Deaths/1M pop', 'Active Cases/1M pop'], ['', '', 'North America', '', '103,143,208', '', '1,479,512', '', '97,000,537', '', '4,663,159', '8,179', '', '', '', '', '', 'North America', '', '', '', '', '', '', ''], ['', '', 'Asia', '', '158,842,694', '+42,438', '1,435,027', '+32', '152,797,714', '+63,660', '4,609,953', '10,581', '', '', '', '', '', 'Asia', '', '', '', '', '', '', ''], ['', '', 'South America', '', '58,405,997', '', '1,300,973', '', '55,432,640', '', '1,672,384', '10,526', '', '', '', '', '', 'South America', '', '', '', '', '', '', ''], ['', '', 'Europe', '', '198,761,428', '', '1,847,603', '', '190,290,528', '+34,430', '6,623,297', '5,758', '', '', '', '', '', 'Europe', '', '', '', '', '', '', ''], ['', '', 'Oceania', '', '9,185,805', '+14,647', '13,034', '+12', '8,842,533', '+4,482', '330,238', '120', '', '', '', '', '', 'Australia/Oceania', '', '', '', '', '', '', ''], ['', '', 'Africa', '', '12,205,182', '', '255,310', '', '11,410,731', '', '539,141', '975', '', '', '', '', '', 'Africa', '', '', '', '', '', '', ''], ['', '', '', '', '721', '', '15', '', '706', '', '0', '0', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['', 'World', '540,545,035', '+57,085', '6,331,474', '+44', '515,775,389', '+102,545', '18,438,172', '36,139', '69,347', '812.3', '', '', '', 'All', '', '', '', '', '', '', ''], ['1', 'USA', '87,321,703', '', '1,035,847 ', '', '83,159,792', '', '3,126,064', '2,812', '260,840', '3,094', '1,039,574,344', '3,105,329', '334,771,130 ', 'North America', '43230', '', '', '9,338'], ['2', 'India', '43,232,004', '', '524,761 ', '', '42,652,743', '', '54,500', '698', '30,741', '373', '854,859,461', '607,858', '1,406,347,202 ', 'Asia', '332,6802', '', '', '39'], ['3', 'Brazil', '31,456,865', '', '668,177 ', '', '30,182,173', '', '606,515', '8,318', '145,976', '3,101', '63,776,166', '295,955', '215,493,041 ', 'South America', '73233', '', '', '2,815'], ['4', 'France', '29,849,919', '', '148,749 ', '', '29,210,587', '', '490,583', '869', '455,349', '2,269', '271,490,188', '4,141,480', '65,553,913 ', 'Europe', '24410', '', '', '7,484'], ['5', 'Germany', '26,847,783', '', '140,183 ', '', '25,882,900', '', '824,700', '631', '318,464', '1,663', '122,332,384', '1,451,085', '84,304,052 ', 'Europe', '36011', '', '', '9,782'], ['6', 'UK', '22,382,352', '', '179,217 ', '', '22,037,192', '+9,380', '165,943', '188', '326,376', '2,613', '522,526,476', '7,619,407', '68,578,364 ', 'Europe', '33830', '', '', '2,420'], ['7', 'Russia', '18,376,587', '', '380,020 ', '', '17,794,561', '', '202,006', '2,300', '125,819', '2,602', '273,400,000', '1,871,886', '146,055,938 ', 'Europe', '83841', '', '', '1,383'], ['8', 'S. Korea', '18,229,288', '+3,828', '24,388 ', '+17', '18,012,349', '+18,777', '192,551', '95', '354,967', '475', '15,804,065', '307,742', '51,354,840 ', 'Asia', '32,1063', '75', '0.3', '3,749'], ['9', 'Italy', '17,653,375', '', '167,391 ', '', '16,863,770', '', '622,214', '183', '292,811', '2,776', '223,025,536', '3,699,259', '60,289,249 ', 'Europe', '33600', '', '', '10,320'], ['10', 'Turkey', '15,072,747', '', '98,965 ', '', '14,971,256', '', '2,526', '975', '175,059', '1,149', '162,743,369', '1,890,142', '86,101,118 ', 'Asia', '68701', '', '', '29'], ['11', 'Spain', '12,478,994', '', '107,108 ', '', '11,939,322', '', '432,564', '339', '266,703', '2,289', '471,036,328', '10,067,044', '46,789,933 ', 'Europe', '44370', '', '', '9,245'], ['12', 'Vietnam', '10,731,812', '', '43,083 ', '', '9,553,193', '', '1,135,536', '24', '108,359', '435', '85,819,388', '866,521', '99,039,045 ', 'Asia', '92,2991', '', '', '11,466'], ['13', 'Argentina', '9,276,618', '', '128,973 ', '', '8,895,999', '', '251,646', '344', '201,661', '2,804', '35,716,069', '776,419', '46,001,003 ', 'South America', '53571', '', '', '5,470'], ['14', 'Japan', '9,038,604', '', '30,879 ', '', '8,844,362', '', '163,363', '66', '71,892', '246', '53,936,990', '429,008', '125,724,945 ', 'Asia', '144,0722', '', '', '1,299'], ['15', 'Netherlands', '8,101,839', '', '22,332 ', '', '8,044,784', '+1,273', '34,723', '33', '470,805', '1,298', '21,107,399', '1,226,570', '17,208,476 ', 'Europe', '27711', '', '', '2,018'], ['16', 'Australia', '7,625,528', '+10,129', '9,053 ', '+6', '7,388,112', '', '228,363', '87', '292,453', '347', '72,755,770', '2,790,321', '26,074,334 ', 'Australia/Oceania', '32,8800', '388', '0.2', '8,758'], ['17', 'Iran', '7,233,688', '', '141,350 ', '', '7,058,972', '', '33,366', '372', '84,034', '1,642', '52,298,398', '607,554', '86,080,275 ', 'Asia', '126092', '', '', '388'], ['18', 'Colombia', '6,117,847', '', '139,894 ', '', '5,943,925', '', '34,028', '342', '117,796', '2,694', '35,175,528', '677,287', '51,935,897 ', 'South America', '83711', '', '', '655'], ['19', 'Indonesia', '6,060,488', '', '156,643 ', '', '5,899,111', '', '4,734', '2,771', '21,711', '561', '99,560,389', '356,669', '279,139,352 ', 'Asia', '461,7823', '', '', '17'], ['20', 'Poland', '6,010,045', '', '116,371 ', '', '5,335,557', '', '558,117', '408', '159,138', '3,081', '36,410,576', '964,106', '37,766,148 ', 'Europe', '63251', '', '', '14,778'], ['21', 'Mexico', '5,821,262', '', '325,186 ', '', '5,085,666', '', '410,410', '4,798', '44,247', '2,472', '16,143,751', '122,707', '131,562,873 ', 'North America', '234058', '', '', '3,119'], ['22', 'Ukraine', '5,014,929', '', '108,605 ', '', 'N/A', 'N/A', 'N/A', '177', '116,022', '2,513', '19,521,252', '451,632', '43,223,844 ', 'Europe', '93982', '', '', '19,626'], ['23', 'Portugal', '4,917,127', '', '23,531 ', '', '4,281,372', '+19,232', '612,224', '61', '484,972', '2,321', '42,825,431', '4,223,831', '10,139,001 ', 'Europe', '24310', '', '', '60,383'], ['24', 'Malaysia', '4,526,298', '', '35,712 ', '', '4,468,191', '', '22,395', '26', '136,453', '1,077', '60,330,396', '1,818,762', '33,171,141 ', 'Asia', '79291', '', '', '675'], ['25', 'Thailand', '4,486,664', '+1,801', '30,352 ', '+15', '4,434,529', '+2,330', '21,783', '1,496', '63,967', '433', '17,270,775', '246,233', '70,140,005 ', 'Asia', '162,3114', '26', '0.2', '311'], ['26', 'DPRK', '4,469,520', '+36,720', '72 ', '', '4,404,210', '+42,650', '65,238', '', '171,917', '3', '', '', '25,998,153 ', 'Asia', '6361,085', '1,412', '', '2,509'], ['27', 'Austria', '4,291,416', '', '18,697 ', '', '4,228,720', '', '43,999', '33', '471,265', '2,053', '188,725,160', '20,724,977', '9,106,170 ', 'Europe', '24870', '', '', '4,832'], ['28', 'Israel', '4,183,485', '', '10,882 ', '', '4,144,910', '', '27,693', '150', '448,583', '1,167', '41,373,364', '4,436,346', '9,326,000 ', 'Asia', '28570', '', '', '2,969'], ['29', 'Belgium', '4,170,252', '', '31,816 ', '', '4,087,206', '+2,625', '51,230', '66', '356,812', '2,722', '34,197,937', '2,926,014', '11,687,549 ', 'Europe', '33670', '', '', '4,383'], ['30', 'South Africa', '3,978,590', '', '101,484 ', '', '3,854,873', '', '22,233', '192', '65,480', '1,670', '25,495,097', '419,600', '60,760,537 ', 'Africa', '155992', '', '', '366'], ['31', 'Czechia', '3,922,968', '', '40,301 ', '', '3,881,515', '', '1,152', '4', '365,010', '3,750', '55,461,297', '5,160,367', '10,747,550 ', 'Europe', '32670', '', '', '107'], ['32', 'Canada', '3,897,450', '', '41,519 ', '', '3,545,851', '', '310,080', '252', '101,537', '1,082', '62,220,040', '1,620,961', '38,384,656 ', 'North America', '109251', '', '', '8,078'], ['33', 'Chile', '3,820,009', '', '58,095 ', '', '3,537,873', '', '224,041', '152', '196,555', '2,989', '39,375,938', '2,026,053', '19,434,799 ', 'South America', '53350', '', '', '11,528'], ['34', 'Philippines', '3,693,222', '', '60,461 ', '', '3,629,843', '', '2,918', '440', '32,854', '538', '30,426,763', '270,670', '112,412,844 ', 'Asia', '301,8594', '', '', '26'], ['35', 'Switzerland', '3,667,742', '', '13,967 ', '', '3,624,223', '+1,695', '29,552', '44', '417,857', '1,591', '21,153,745', '2,409,995', '8,777,507 ', 'Europe', '26280', '', '', '3,367'], ['36', 'Peru', '3,590,882', '', '213,324 ', '', '3,367,023', '', '10,535', '140', '106,040', '6,300', '31,006,663', '915,634', '33,863,613 ', 'South America', '91591', '', '', '311'], ['37', 'Greece', '3,500,489', '', '30,020 ', '', '3,423,217', '', '47,252', '110', '339,055', '2,908', '83,576,762', '8,095,197', '10,324,241 ', 'Europe', '33440', '', '', '4,577'], ['38', 'Denmark', '2,990,478', '', '6,404 ', '', '2,976,888', '', '7,186', '9', '512,788', '1,098', '127,515,122', '21,865,475', '5,831,802 ', 'Europe', '29110', '', '', '1,232'], ['39', 'Romania', '2,912,705', '', '65,714 ', '', '2,842,599', '', '4,392', '48', '153,392', '3,461', '23,326,374', '1,228,439', '18,988,638 ', 'Europe', '72891', '', '', '231'], ['40', 'Taiwan', '2,892,263', '', '4,171 ', '', '1,382,413', '', '1,505,679', '', '121,013', '175', '19,545,394', '817,783', '23,900,461 ', 'Asia', '85,7301', '', '', '62,998'], ['41', 'Sweden', '2,510,930', '', '19,016 ', '', '2,486,355', '+228', '5,559', '6', '245,651', '1,860', '18,622,701', '1,821,909', '10,221,530 ', 'Europe', '45381', '', '', '544'], ['42', 'Iraq', '2,329,813', '', '25,222 ', '', '2,303,211', '', '1,380', '11', '55,505', '601', '18,642,914', '444,147', '41,974,669 ', 'Asia', '181,6642', '', '', '33'], ['43', 'Serbia', '2,020,338', '', '16,101 ', '', '1,999,903', '', '4,334', '12', '233,052', '1,857', '9,786,426', '1,128,891', '8,669,062 ', 'Europe', '45381', '', '', '500'], ['44', 'Bangladesh', '1,954,115', '', '29,131 ', '', '1,905,266', '', '19,718', '1,328', '11,640', '174', '14,184,474', '84,494', '167,875,067 ', 'Asia', '865,76312', '', '', '117'], ['45', 'Hungary', '1,921,486', '', '46,571 ', '', '1,853,094', '', '21,821', '8', '199,890', '4,845', '11,394,556', '1,185,360', '9,612,738 ', 'Europe', '52061', '', '', '2,270'], ['46', 'Slovakia', '1,791,192', '', '20,116 ', '', '1,769,321', '', '1,755', '17', '327,770', '3,681', '7,158,886', '1,310,005', '5,464,776 ', 'Europe', '32721', '', '', '321'], ['47', 'Jordan', '1,697,271', '', '14,068 ', '', '1,682,962', '', '241', '124', '163,202', '1,353', '16,834,239', '1,618,708', '10,399,799 ', 'Asia', '67391', '', '', '23'], ['48', 'Georgia', '1,658,240', '', '16,826 ', '', '1,637,293', '', '4,121', '', '417,240', '4,234', '16,920,079', '4,257,369', '3,974,304 ', 'Asia', '22360', '', '', '1,037'], ['49', 'Ireland', '1,570,519', '', '7,383 ', '', '1,546,833', '', '16,303', '24', '311,310', '1,463', '12,282,059', '2,434,560', '5,044,878 ', 'Europe', '36830', '', '', '3,232'], ['50', 'Pakistan', '1,531,177', '', '30,381 ', '', '1,496,123', '', '4,673', '47', '6,680', '133', '28,738,295', '125,375', '229,219,201 ', 'Asia', '1507,5458', '', '', '20'], ['51', 'Norway', '1,436,855', '', '3,210 ', '', '1,429,477', '', '4,168', '20', '261,078', '583', '11,002,430', '1,999,153', '5,503,546 ', 'Europe', '41,7151', '', '', '757'], ['52', 'Singapore', '1,341,256', '', '1,397 ', '', '1,260,635', '', '79,224', '4', '225,813', '235', '23,877,882', '4,020,065', '5,939,675 ', 'Asia', '44,2520', '', '', '13,338'], ['53', 'Kazakhstan', '1,305,862', '', '13,662 ', '', '1,292,103', '', '97', '24', '67,968', '711', '11,575,012', '602,464', '19,212,778 ', 'Asia', '151,4062', '', '', '5'], ['54', 'New Zealand', '1,242,497', '+4,518', '1,267 ', '+6', '1,199,266', '+4,482', '41,964', '', '248,395', '253', '71,423,774', '14,278,758', '5,002,100 ', 'Australia/Oceania', '43,9480', '903', '1', '8,389'], ['55', 'Hong Kong', '1,219,175', '', '9,390 ', '', '1,196,929', '', '12,856', '5', '160,100', '1,233', '49,428,776', '6,490,913', '7,615,073 ', 'Asia', '68110', '', '', '1,688'], ['56', 'Morocco', '1,175,604', '', '16,082 ', '', '1,153,738', '', '5,784', '293', '31,134', '426', '11,738,659', '310,876', '37,759,993 ', 'Africa', '322,3483', '', '', '153'], ['57', 'Bulgaria', '1,166,901', '', '37,196 ', '', '1,061,038', '', '68,667', '26', '170,427', '5,433', '10,046,216', '1,467,257', '6,846,939 ', 'Europe', '61841', '', '', '10,029'], ['58', 'Croatia', '1,139,816', '', '16,019 ', '', '1,121,901', '', '1,896', '5', '281,010', '3,949', '4,904,530', '1,209,163', '4,056,135 ', 'Europe', '42531', '', '', '467'], ['59', 'Finland', '1,114,573', '', '4,714 ', '', 'N/A', 'N/A', 'N/A', '21', '200,555', '848', '10,977,262', '1,975,241', '5,557,430 ', 'Europe', '51,1791', '', '', '191,430'], ['60', 'Cuba', '1,105,612', '', '8,529 ', '', '1,096,919', '', '164', '23', '97,728', '754', '13,852,049', '1,224,415', '11,313,196 ', 'North America', '101,3261', '', '', '14'], ['61', 'Lebanon', '1,101,109', '', '10,445 ', '', '1,087,356', '', '3,308', '186', '162,739', '1,544', '4,795,578', '708,763', '6,766,121 ', 'Asia', '66481', '', '', '489'], ['62', 'Lithuania', '1,064,011', '', '9,153 ', '', '1,037,322', '', '17,536', '8', '401,726', '3,456', '9,989,932', '3,771,777', '2,648,601 ', 'Europe', '22890', '', '', '6,621'], ['63', 'Tunisia', '1,043,540', '', '28,648 ', '', 'N/A', 'N/A', 'N/A', '29', '86,538', '2,376', '4,640,840', '384,853', '12,058,729 ', 'Africa', '124213', '', '', '-983.85'], ['64', 'Slovenia', '1,028,299', '', '6,644 ', '', '1,017,602', '', '4,053', '6', '494,495', '3,195', '2,673,070', '1,285,443', '2,079,493 ', 'Europe', '23131', '', '', '1,949'], ['65', 'Belarus', '982,867', '', '6,978 ', '', 'N/A', 'N/A', 'N/A', '', '104,081', '739', '13,220,483', '1,399,987', '9,443,289 ', 'Europe', '101,3531', '', '', '5,014'], ['66', 'Nepal', '979,262', '', '11,952 ', '', '967,204', '', '106', '', '32,475', '396', '5,728,570', '189,976', '30,154,226 ', 'Asia', '312,5235', '', '', '4'], ['67', 'Uruguay', '934,961', '', '7,262 ', '', '920,062', '', '7,637', '18', '267,353', '2,077', '6,114,822', '1,748,540', '3,497,102 ', 'South America', '44821', '', '', '2,184'], ['68', 'Mongolia', '925,227', '', '2,179 ', '', 'N/A', 'N/A', 'N/A', '192', '273,672', '645', '4,030,048', '1,192,044', '3,380,787 ', 'Asia', '41,5521', '', '', '180,370'], ['69', 'UAE', '917,496', '', '2,305 ', '', '899,282', '', '15,909', '', '90,640', '228', '165,144,844', '16,314,764', '10,122,417 ', 'Asia', '114,3920', '', '', '1,572'], ['70', 'Bolivia', '912,272', '', '21,951 ', '', '875,079', '', '15,242', '220', '76,136', '1,832', '2,705,422', '225,787', '11,982,173 ', 'South America', '135464', '', '', '1,272'], ['71', 'Costa Rica', '904,934', '', '8,525 ', '', '860,711', '', '35,698', '52', '174,548', '1,644', '4,659,757', '898,797', '5,184,435 ', 'North America', '66081', '', '', '6,886'], ['72', 'Panama', '889,960', '', '8,298 ', '', '855,970', '', '25,692', '16', '200,142', '1,866', '6,403,309', '1,440,033', '4,446,639 ', 'North America', '55361', '', '', '5,778'], ['73', 'Ecuador', '887,478', '', '35,652 ', '', 'N/A', 'N/A', 'N/A', '759', '48,861', '1,963', '2,470,170', '135,999', '18,163,202 ', 'South America', '205097', '', '', '22,460'], ['74', 'Guatemala', '871,112', '', '18,287 ', '', '845,301', '', '7,524', '5', '46,938', '985', '4,754,409', '256,179', '18,558,966 ', 'North America', '211,0154', '', '', '405'], ['75', 'Latvia', '830,281', '', '5,837 ', '', '822,254', '', '2,190', '6', '449,837', '3,162', '7,283,849', '3,946,309', '1,845,737 ', 'Europe', '23160', '', '', '1,187'], ['76', 'Azerbaijan', '792,847', '', '9,714 ', '', '783,019', '', '114', '', '76,851', '942', '6,901,005', '668,921', '10,316,617 ', 'Asia', '131,0621', '', '', '11'], ['77', 'Saudi Arabia', '777,795', '', '9,173 ', '', '759,567', '', '9,055', '96', '21,686', '256', '42,910,389', '1,196,392', '35,866,511 ', 'Asia', '463,9101', '', '', '252'], ['78', 'Sri Lanka', '663,950', '', '16,519 ', '', '646,981', '', '450', '', '30,756', '765', '6,486,117', '300,456', '21,587,560 ', 'Asia', '331,3073', '', '', '21'], ['79', 'Paraguay', '652,044', '', '18,932 ', '', '624,673', '', '8,439', '2', '89,289', '2,592', '2,646,163', '362,357', '7,302,646 ', 'South America', '113863', '', '', '1,156'], ['80', 'Kuwait', '636,240', '', '2,555 ', '', '631,350', '', '2,335', '22', '144,824', '582', '8,149,895', '1,855,119', '4,393,193 ', 'Asia', '71,7191', '', '', '532'], ['81', 'Myanmar', '613,443', '', '19,434 ', '', '592,424', '', '1,585', '', '11,130', '353', '8,276,726', '150,164', '55,117,987 ', 'Asia', '902,8367', '', '', '29'], ['82', 'Bahrain', '595,787', '', '1,489 ', '', '586,597', '', '7,701', '5', '328,009', '820', '9,909,427', '5,455,615', '1,816,372 ', 'Asia', '31,2200', '', '', '4,240'], ['83', 'Dominican Republic', '590,764', '', '4,380 ', '', '583,196', '', '3,188', '14', '53,419', '396', '3,401,291', '307,555', '11,059,123 ', 'North America', '192,5253', '', '', '288'], ['84', 'Palestine', '582,669', '', '5,356 ', '', '577,132', '', '181', '17', '109,285', '1,005', '3,078,533', '577,410', '5,331,624 ', 'Asia', '99952', '', '', '34'], ['85', 'Estonia', '577,655', '', '2,574 ', '', '520,451', '', '54,630', '5', '434,894', '1,938', '3,386,999', '2,549,938', '1,328,267 ', 'Europe', '25160', '', '', '41,129'], ['86', 'Venezuela', '524,216', '', '5,723 ', '', '517,368', '', '1,125', '230', '18,537', '202', '3,359,014', '118,779', '28,279,553 ', 'South America', '544,9418', '', '', '40'], ['87', 'Moldova', '519,228', '', '11,551 ', '', '504,142', '', '3,535', '49', '129,297', '2,876', '3,216,305', '800,920', '4,015,765 ', 'Europe', '83481', '', '', '880'], ['88', 'Egypt', '515,645', '', '24,613 ', '', '442,182', '', '48,850', '122', '4,861', '232', '3,693,367', '34,816', '106,081,550 ', 'Africa', '2064,31029', '', '', '460'], ['89', 'Libya', '502,040', '', '6,430 ', '', '490,973', '', '4,637', '101', '71,184', '912', '2,477,219', '351,244', '7,052,705 ', 'Africa', '141,0973', '', '', '657'], ['90', 'Cyprus', '491,777', '', '1,067 ', '', '124,370', '', '366,340', '60', '401,639', '871', '9,477,138', '7,740,079', '1,224,424 ', 'Asia', '21,1480', '', '', '299,194'], ['91', 'Ethiopia', '478,963', '', '7,516 ', '', '456,719', '', '14,728', '22', '3,975', '62', '4,984,382', '41,367', '120,491,426 ', 'Africa', '25216,03124', '', '', '122'], ['92', 'Honduras', '425,655', '', '10,902 ', '', '132,430', '', '282,323', '105', '41,688', '1,068', '1,387,113', '135,852', '10,210,450 ', 'North America', '249377', '', '', '27,650'], ['93', 'Armenia', '423,006', '', '8,629 ', '', '412,661', '', '1,716', '', '142,235', '2,901', '3,109,931', '1,045,708', '2,973,995 ', 'Asia', '73451', '', '', '577'], ['94', 'RÃ©union', '418,585', '', '796 ', '', '415,360', '', '2,429', '10', '461,140', '877', '1,603,660', '1,766,696', '907,717 ', 'Africa', '21,1401', '', '', '2,676'], ['95', 'Oman', '389,758', '', '4,260 ', '', '384,669', '', '829', '2', '72,733', '795', '25,000,000', '4,665,281', '5,358,734 ', 'Asia', '141,2580', '', '', '155'], ['96', 'Bosnia and Herzegovina', '378,083', '', '15,793 ', '', 'N/A', 'N/A', 'N/A', '', '116,649', '4,873', '1,782,014', '549,798', '3,241,214 ', 'Europe', '92052', '', '', '52,472'], ['97', 'Qatar', '372,261', '', '677 ', '', '369,100', '', '2,484', '', '132,581', '241', '3,586,479', '1,277,325', '2,807,805 ', 'Asia', '84,1471', '', '', '885'], ['98', 'Kenya', '326,932', '', '5,651 ', '', '319,519', '', '1,762', '', '5,831', '101', '3,701,693', '66,018', '56,070,618 ', 'Africa', '1729,92215', '', '', '31'], ['99', 'Zambia', '323,058', '', '3,989 ', '', '318,016', '', '1,053', '', '16,667', '206', '3,504,021', '180,775', '19,383,333 ', 'Africa', '604,8596', '', '', '54'], ['100', 'North Macedonia', '312,538', '', '9,316 ', '', '302,807', '', '415', '', '150,027', '4,472', '2,055,472', '986,686', '2,083,208 ', 'Europe', '72241', '', '', '199'], ['101', 'Botswana', '310,431', '', '2,701 ', '', '304,887', '', '2,843', '1', '127,028', '1,105', '2,026,898', '829,402', '2,443,806 ', 'Africa', '89051', '', '', '1,163'], ['102', 'Albania', '276,731', '', '3,497 ', '', '272,893', '', '341', '2', '96,365', '1,218', '1,835,130', '639,040', '2,871,697 ', 'Europe', '108212', '', '', '119'], ['

In [12]:
final_data = []
for j in data:
  if j[0] != '':
    final_data.append(j)

print(final_data)

[['#', 'Country,Other', 'TotalCases', 'NewCases', 'TotalDeaths', 'NewDeaths', 'TotalRecovered', 'NewRecovered', 'ActiveCases', 'Serious,Critical', 'Tot\xa0Cases/1M pop', 'Deaths/1M pop', 'TotalTests', 'Tests/', '1M pop', '', 'Population', 'Continent', '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl', 'New Cases/1M pop', 'New Deaths/1M pop', 'Active Cases/1M pop'], ['1', 'USA', '87,321,703', '', '1,035,847 ', '', '83,159,792', '', '3,126,064', '2,812', '260,840', '3,094', '1,039,574,344', '3,105,329', '334,771,130 ', 'North America', '43230', '', '', '9,338'], ['2', 'India', '43,232,004', '', '524,761 ', '', '42,652,743', '', '54,500', '698', '30,741', '373', '854,859,461', '607,858', '1,406,347,202 ', 'Asia', '332,6802', '', '', '39'], ['3', 'Brazil', '31,456,865', '', '668,177 ', '', '30,182,173', '', '606,515', '8,318', '145,976', '3,101', '63,776,166', '295,955', '215,493,041 ', 'South America', '73233', '', '', '2,815'], ['4', 'France', '29,849,919', '', '148,749 ', '', '29,210,587', '', '490,583', '869', '455,349', '2,269', '271,490,188', '4,141,480', '65,553,913 ', 'Europe', '24410', '', '', '7,484'], ['5', 'Germany', '26,847,783', '', '140,183 ', '', '25,882,900', '', '824,700', '631', '318,464', '1,663', '122,332,384', '1,451,085', '84,304,052 ', 'Europe', '36011', '', '', '9,782'], ['6', 'UK', '22,382,352', '', '179,217 ', '', '22,037,192', '+9,380', '165,943', '188', '326,376', '2,613', '522,526,476', '7,619,407', '68,578,364 ', 'Europe', '33830', '', '', '2,420'], ['7', 'Russia', '18,376,587', '', '380,020 ', '', '17,794,561', '', '202,006', '2,300', '125,819', '2,602', '273,400,000', '1,871,886', '146,055,938 ', 'Europe', '83841', '', '', '1,383'], ['8', 'S. Korea', '18,229,288', '+3,828', '24,388 ', '+17', '18,012,349', '+18,777', '192,551', '95', '354,967', '475', '15,804,065', '307,742', '51,354,840 ', 'Asia', '32,1063', '75', '0.3', '3,749'], ['9', 'Italy', '17,653,375', '', '167,391 ', '', '16,863,770', '', '622,214', '183', '292,811', '2,776', '223,025,536', '3,699,259', '60,289,249 ', 'Europe', '33600', '', '', '10,320'], ['10', 'Turkey', '15,072,747', '', '98,965 ', '', '14,971,256', '', '2,526', '975', '175,059', '1,149', '162,743,369', '1,890,142', '86,101,118 ', 'Asia', '68701', '', '', '29'], ['11', 'Spain', '12,478,994', '', '107,108 ', '', '11,939,322', '', '432,564', '339', '266,703', '2,289', '471,036,328', '10,067,044', '46,789,933 ', 'Europe', '44370', '', '', '9,245'], ['12', 'Vietnam', '10,731,812', '', '43,083 ', '', '9,553,193', '', '1,135,536', '24', '108,359', '435', '85,819,388', '866,521', '99,039,045 ', 'Asia', '92,2991', '', '', '11,466'], ['13', 'Argentina', '9,276,618', '', '128,973 ', '', '8,895,999', '', '251,646', '344', '201,661', '2,804', '35,716,069', '776,419', '46,001,003 ', 'South America', '53571', '', '', '5,470'], ['14', 'Japan', '9,038,604', '', '30,879 ', '', '8,844,362', '', '163,363', '66', '71,892', '246', '53,936,990', '429,008', '125,724,945 ', 'Asia', '144,0722', '', '', '1,299'], ['15', 'Netherlands', '8,101,839', '', '22,332 ', '', '8,044,784', '+1,273', '34,723', '33', '470,805', '1,298', '21,107,399', '1,226,570', '17,208,476 ', 'Europe', '27711', '', '', '2,018'], ['16', 'Australia', '7,625,528', '+10,129', '9,053 ', '+6', '7,388,112', '', '228,363', '87', '292,453', '347', '72,755,770', '2,790,321', '26,074,334 ', 'Australia/Oceania', '32,8800', '388', '0.2', '8,758'], ['17', 'Iran', '7,233,688', '', '141,350 ', '', '7,058,972', '', '33,366', '372', '84,034', '1,642', '52,298,398', '607,554', '86,080,275 ', 'Asia', '126092', '', '', '388'], ['18', 'Colombia', '6,117,847', '', '139,894 ', '', '5,943,925', '', '34,028', '342', '117,796', '2,694', '35,175,528', '677,287', '51,935,897 ', 'South America', '83711', '', '', '655'], ['19', 'Indonesia', '6,060,488', '', '156,643 ', '', '5,899,111', '', '4,734', '2,771', '21,711', '561', '99,560,389', '356,669', '279,139,352 ', 'Asia', '461,7823', '', '', '17'], ['20', 'Poland', '6,010,045', '', '116,371 ', '', '5,335,557', '', '558,117', '408', '159,138', '3,081', '36,410,576', '964,106', '37,766,148 ', 'Europe', '63251', '', '', '14,778'], ['21', 'Mexico', '5,821,262', '', '325,186 ', '', '5,085,666', '', '410,410', '4,798', '44,247', '2,472', '16,143,751', '122,707', '131,562,873 ', 'North America', '234058', '', '', '3,119'], ['22', 'Ukraine', '5,014,929', '', '108,605 ', '', 'N/A', 'N/A', 'N/A', '177', '116,022', '2,513', '19,521,252', '451,632', '43,223,844 ', 'Europe', '93982', '', '', '19,626'], ['23', 'Portugal', '4,917,127', '', '23,531 ', '', '4,281,372', '+19,232', '612,224', '61', '484,972', '2,321', '42,825,431', '4,223,831', '10,139,001 ', 'Europe', '24310', '', '', '60,383'], ['24', 'Malaysia', '4,526,298', '', '35,712 ', '', '4,468,191', '', '22,395', '26', '136,453', '1,077', '60,330,396', '1,818,762', '33,171,141 ', 'Asia', '79291', '', '', '675'], ['25', 'Thailand', '4,486,664', '+1,801', '30,352 ', '+15', '4,434,529', '+2,330', '21,783', '1,496', '63,967', '433', '17,270,775', '246,233', '70,140,005 ', 'Asia', '162,3114', '26', '0.2', '311'], ['26', 'DPRK', '4,469,520', '+36,720', '72 ', '', '4,404,210', '+42,650', '65,238', '', '171,917', '3', '', '', '25,998,153 ', 'Asia', '6361,085', '1,412', '', '2,509'], ['27', 'Austria', '4,291,416', '', '18,697 ', '', '4,228,720', '', '43,999', '33', '471,265', '2,053', '188,725,160', '20,724,977', '9,106,170 ', 'Europe', '24870', '', '', '4,832'], ['28', 'Israel', '4,183,485', '', '10,882 ', '', '4,144,910', '', '27,693', '150', '448,583', '1,167', '41,373,364', '4,436,346', '9,326,000 ', 'Asia', '28570', '', '', '2,969'], ['29', 'Belgium', '4,170,252', '', '31,816 ', '', '4,087,206', '+2,625', '51,230', '66', '356,812', '2,722', '34,197,937', '2,926,014', '11,687,549 ', 'Europe', '33670', '', '', '4,383'], ['30', 'South Africa', '3,978,590', '', '101,484 ', '', '3,854,873', '', '22,233', '192', '65,480', '1,670', '25,495,097', '419,600', '60,760,537 ', 'Africa', '155992', '', '', '366'], ['31', 'Czechia', '3,922,968', '', '40,301 ', '', '3,881,515', '', '1,152', '4', '365,010', '3,750', '55,461,297', '5,160,367', '10,747,550 ', 'Europe', '32670', '', '', '107'], ['32', 'Canada', '3,897,450', '', '41,519 ', '', '3,545,851', '', '310,080', '252', '101,537', '1,082', '62,220,040', '1,620,961', '38,384,656 ', 'North America', '109251', '', '', '8,078'], ['33', 'Chile', '3,820,009', '', '58,095 ', '', '3,537,873', '', '224,041', '152', '196,555', '2,989', '39,375,938', '2,026,053', '19,434,799 ', 'South America', '53350', '', '', '11,528'], ['34', 'Philippines', '3,693,222', '', '60,461 ', '', '3,629,843', '', '2,918', '440', '32,854', '538', '30,426,763', '270,670', '112,412,844 ', 'Asia', '301,8594', '', '', '26'], ['35', 'Switzerland', '3,667,742', '', '13,967 ', '', '3,624,223', '+1,695', '29,552', '44', '417,857', '1,591', '21,153,745', '2,409,995', '8,777,507 ', 'Europe', '26280', '', '', '3,367'], ['36', 'Peru', '3,590,882', '', '213,324 ', '', '3,367,023', '', '10,535', '140', '106,040', '6,300', '31,006,663', '915,634', '33,863,613 ', 'South America', '91591', '', '', '311'], ['37', 'Greece', '3,500,489', '', '30,020 ', '', '3,423,217', '', '47,252', '110', '339,055', '2,908', '83,576,762', '8,095,197', '10,324,241 ', 'Europe', '33440', '', '', '4,577'], ['38', 'Denmark', '2,990,478', '', '6,404 ', '', '2,976,888', '', '7,186', '9', '512,788', '1,098', '127,515,122', '21,865,475', '5,831,802 ', 'Europe', '29110', '', '', '1,232'], ['39', 'Romania', '2,912,705', '', '65,714 ', '', '2,842,599', '', '4,392', '48', '153,392', '3,461', '23,326,374', '1,228,439', '18,988,638 ', 'Europe', '72891', '', '', '231'], ['40', 'Taiwan', '2,892,263', '', '4,171 ', '', '1,382,413', '', '1,505,679', '', '121,013', '175', '19,545,394', '817,783', '23,900,461 ', 'Asia', '85,7301', '', '', '62,998'], ['41', 'Sweden', '2,510,930', '', '19,016 ', '', '2,486,355', '+228', '5,559', '6', '245,651', '1,860', '18,622,701', '1,821,909', '10,221,530 ', 'Europe', '45381', '', '', '544'], ['42', 'Iraq', '2,329,813', '', '25,222 ', '', '2,303,211', '', '1,380', '11', '55,505', '601', '18,642,914', '444,147', '41,974,669 ', 'Asia', '181,6642', '', '', '33'], ['43', 'Serbia', '2,020,338', '', '16,101 ', '', '1,999,903', '', '4,334', '12', '233,052', '1,857', '9,786,426', '1,128,891', '8,669,062 ', 'Europe', '45381', '', '', '500'], ['44', 'Bangladesh', '1,954,115', '', '29,131 ', '', '1,905,266', '', '19,718', '1,328', '11,640', '174', '14,184,474', '84,494', '167,875,067 ', 'Asia', '865,76312', '', '', '117'], ['45', 'Hungary', '1,921,486', '', '46,571 ', '', '1,853,094', '', '21,821', '8', '199,890', '4,845', '11,394,556', '1,185,360', '9,612,738 ', 'Europe', '52061', '', '', '2,270'], ['46', 'Slovakia', '1,791,192', '', '20,116 ', '', '1,769,321', '', '1,755', '17', '327,770', '3,681', '7,158,886', '1,310,005', '5,464,776 ', 'Europe', '32721', '', '', '321'], ['47', 'Jordan', '1,697,271', '', '14,068 ', '', '1,682,962', '', '241', '124', '163,202', '1,353', '16,834,239', '1,618,708', '10,399,799 ', 'Asia', '67391', '', '', '23'], ['48', 'Georgia', '1,658,240', '', '16,826 ', '', '1,637,293', '', '4,121', '', '417,240', '4,234', '16,920,079', '4,257,369', '3,974,304 ', 'Asia', '22360', '', '', '1,037'], ['49', 'Ireland', '1,570,519', '', '7,383 ', '', '1,546,833', '', '16,303', '24', '311,310', '1,463', '12,282,059', '2,434,560', '5,044,878 ', 'Europe', '36830', '', '', '3,232'], ['50', 'Pakistan', '1,531,177', '', '30,381 ', '', '1,496,123', '', '4,673', '47', '6,680', '133', '28,738,295', '125,375', '229,219,201 ', 'Asia', '1507,5458', '', '', '20'], ['51', 'Norway', '1,436,855', '', '3,210 ', '', '1,429,477', '', '4,168', '20', '261,078', '583', '11,002,430', '1,999,153', '5,503,546 ', 'Europe', '41,7151', '', '', '757'], ['52', 'Singapore', '1,341,256', '', '1,397 ', '', '1,260,635', '', '79,224', '4', '225,813', '235', '23,877,882', '4,020,065', '5,939,675 ', 'Asia', '44,2520', '', '', '13,338'], ['53', 'Kazakhstan', '1,305,862', '', '13,662 ', '', '1,292,103', '', '97', '24', '67,968', '711', '11,575,012', '602,464', '19,212,778 ', 'Asia', '151,4062', '', '', '5'], ['54', 'New Zealand', '1,242,497', '+4,518', '1,267 ', '+6', '1,199,266', '+4,482', '41,964', '', '248,395', '253', '71,423,774', '14,278,758', '5,002,100 ', 'Australia/Oceania', '43,9480', '903', '1', '8,389'], ['55', 'Hong Kong', '1,219,175', '', '9,390 ', '', '1,196,929', '', '12,856', '5', '160,100', '1,233', '49,428,776', '6,490,913', '7,615,073 ', 'Asia', '68110', '', '', '1,688'], ['56', 'Morocco', '1,175,604', '', '16,082 ', '', '1,153,738', '', '5,784', '293', '31,134', '426', '11,738,659', '310,876', '37,759,993 ', 'Africa', '322,3483', '', '', '153'], ['57', 'Bulgaria', '1,166,901', '', '37,196 ', '', '1,061,038', '', '68,667', '26', '170,427', '5,433', '10,046,216', '1,467,257', '6,846,939 ', 'Europe', '61841', '', '', '10,029'], ['58', 'Croatia', '1,139,816', '', '16,019 ', '', '1,121,901', '', '1,896', '5', '281,010', '3,949', '4,904,530', '1,209,163', '4,056,135 ', 'Europe', '42531', '', '', '467'], ['59', 'Finland', '1,114,573', '', '4,714 ', '', 'N/A', 'N/A', 'N/A', '21', '200,555', '848', '10,977,262', '1,975,241', '5,557,430 ', 'Europe', '51,1791', '', '', '191,430'], ['60', 'Cuba', '1,105,612', '', '8,529 ', '', '1,096,919', '', '164', '23', '97,728', '754', '13,852,049', '1,224,415', '11,313,196 ', 'North America', '101,3261', '', '', '14'], ['61', 'Lebanon', '1,101,109', '', '10,445 ', '', '1,087,356', '', '3,308', '186', '162,739', '1,544', '4,795,578', '708,763', '6,766,121 ', 'Asia', '66481', '', '', '489'], ['62', 'Lithuania', '1,064,011', '', '9,153 ', '', '1,037,322', '', '17,536', '8', '401,726', '3,456', '9,989,932', '3,771,777', '2,648,601 ', 'Europe', '22890', '', '', '6,621'], ['63', 'Tunisia', '1,043,540', '', '28,648 ', '', 'N/A', 'N/A', 'N/A', '29', '86,538', '2,376', '4,640,840', '384,853', '12,058,729 ', 'Africa', '124213', '', '', '-983.85'], ['64', 'Slovenia', '1,028,299', '', '6,644 ', '', '1,017,602', '', '4,053', '6', '494,495', '3,195', '2,673,070', '1,285,443', '2,079,493 ', 'Europe', '23131', '', '', '1,949'], ['65', 'Belarus', '982,867', '', '6,978 ', '', 'N/A', 'N/A', 'N/A', '', '104,081', '739', '13,220,483', '1,399,987', '9,443,289 ', 'Europe', '101,3531', '', '', '5,014'], ['66', 'Nepal', '979,262', '', '11,952 ', '', '967,204', '', '106', '', '32,475', '396', '5,728,570', '189,976', '30,154,226 ', 'Asia', '312,5235', '', '', '4'], ['67', 'Uruguay', '934,961', '', '7,262 ', '', '920,062', '', '7,637', '18', '267,353', '2,077', '6,114,822', '1,748,540', '3,497,102 ', 'South America', '44821', '', '', '2,184'], ['68', 'Mongolia', '925,227', '', '2,179 ', '', 'N/A', 'N/A', 'N/A', '192', '273,672', '645', '4,030,048', '1,192,044', '3,380,787 ', 'Asia', '41,5521', '', '', '180,370'], ['69', 'UAE', '917,496', '', '2,305 ', '', '899,282', '', '15,909', '', '90,640', '228', '165,144,844', '16,314,764', '10,122,417 ', 'Asia', '114,3920', '', '', '1,572'], ['70', 'Bolivia', '912,272', '', '21,951 ', '', '875,079', '', '15,242', '220', '76,136', '1,832', '2,705,422', '225,787', '11,982,173 ', 'South America', '135464', '', '', '1,272'], ['71', 'Costa Rica', '904,934', '', '8,525 ', '', '860,711', '', '35,698', '52', '174,548', '1,644', '4,659,757', '898,797', '5,184,435 ', 'North America', '66081', '', '', '6,886'], ['72', 'Panama', '889,960', '', '8,298 ', '', '855,970', '', '25,692', '16', '200,142', '1,866', '6,403,309', '1,440,033', '4,446,639 ', 'North America', '55361', '', '', '5,778'], ['73', 'Ecuador', '887,478', '', '35,652 ', '', 'N/A', 'N/A', 'N/A', '759', '48,861', '1,963', '2,470,170', '135,999', '18,163,202 ', 'South America', '205097', '', '', '22,460'], ['74', 'Guatemala', '871,112', '', '18,287 ', '', '845,301', '', '7,524', '5', '46,938', '985', '4,754,409', '256,179', '18,558,966 ', 'North America', '211,0154', '', '', '405'], ['75', 'Latvia', '830,281', '', '5,837 ', '', '822,254', '', '2,190', '6', '449,837', '3,162', '7,283,849', '3,946,309', '1,845,737 ', 'Europe', '23160', '', '', '1,187'], ['76', 'Azerbaijan', '792,847', '', '9,714 ', '', '783,019', '', '114', '', '76,851', '942', '6,901,005', '668,921', '10,316,617 ', 'Asia', '131,0621', '', '', '11'], ['77', 'Saudi Arabia', '777,795', '', '9,173 ', '', '759,567', '', '9,055', '96', '21,686', '256', '42,910,389', '1,196,392', '35,866,511 ', 'Asia', '463,9101', '', '', '252'], ['78', 'Sri Lanka', '663,950', '', '16,519 ', '', '646,981', '', '450', '', '30,756', '765', '6,486,117', '300,456', '21,587,560 ', 'Asia', '331,3073', '', '', '21'], ['79', 'Paraguay', '652,044', '', '18,932 ', '', '624,673', '', '8,439', '2', '89,289', '2,592', '2,646,163', '362,357', '7,302,646 ', 'South America', '113863', '', '', '1,156'], ['80', 'Kuwait', '636,240', '', '2,555 ', '', '631,350', '', '2,335', '22', '144,824', '582', '8,149,895', '1,855,119', '4,393,193 ', 'Asia', '71,7191', '', '', '532'], ['81', 'Myanmar', '613,443', '', '19,434 ', '', '592,424', '', '1,585', '', '11,130', '353', '8,276,726', '150,164', '55,117,987 ', 'Asia', '902,8367', '', '', '29'], ['82', 'Bahrain', '595,787', '', '1,489 ', '', '586,597', '', '7,701', '5', '328,009', '820', '9,909,427', '5,455,615', '1,816,372 ', 'Asia', '31,2200', '', '', '4,240'], ['83', 'Dominican Republic', '590,764', '', '4,380 ', '', '583,196', '', '3,188', '14', '53,419', '396', '3,401,291', '307,555', '11,059,123 ', 'North America', '192,5253', '', '', '288'], ['84', 'Palestine', '582,669', '', '5,356 ', '', '577,132', '', '181', '17', '109,285', '1,005', '3,078,533', '577,410', '5,331,624 ', 'Asia', '99952', '', '', '34'], ['85', 'Estonia', '577,655', '', '2,574 ', '', '520,451', '', '54,630', '5', '434,894', '1,938', '3,386,999', '2,549,938', '1,328,267 ', 'Europe', '25160', '', '', '41,129'], ['86', 'Venezuela', '524,216', '', '5,723 ', '', '517,368', '', '1,125', '230', '18,537', '202', '3,359,014', '118,779', '28,279,553 ', 'South America', '544,9418', '', '', '40'], ['87', 'Moldova', '519,228', '', '11,551 ', '', '504,142', '', '3,535', '49', '129,297', '2,876', '3,216,305', '800,920', '4,015,765 ', 'Europe', '83481', '', '', '880'], ['88', 'Egypt', '515,645', '', '24,613 ', '', '442,182', '', '48,850', '122', '4,861', '232', '3,693,367', '34,816', '106,081,550 ', 'Africa', '2064,31029', '', '', '460'], ['89', 'Libya', '502,040', '', '6,430 ', '', '490,973', '', '4,637', '101', '71,184', '912', '2,477,219', '351,244', '7,052,705 ', 'Africa', '141,0973', '', '', '657'], ['90', 'Cyprus', '491,777', '', '1,067 ', '', '124,370', '', '366,340', '60', '401,639', '871', '9,477,138', '7,740,079', '1,224,424 ', 'Asia', '21,1480', '', '', '299,194'], ['91', 'Ethiopia', '478,963', '', '7,516 ', '', '456,719', '', '14,728', '22', '3,975', '62', '4,984,382', '41,367', '120,491,426 ', 'Africa', '25216,03124', '', '', '122'], ['92', 'Honduras', '425,655', '', '10,902 ', '', '132,430', '', '282,323', '105', '41,688', '1,068', '1,387,113', '135,852', '10,210,450 ', 'North America', '249377', '', '', '27,650'], ['93', 'Armenia', '423,006', '', '8,629 ', '', '412,661', '', '1,716', '', '142,235', '2,901', '3,109,931', '1,045,708', '2,973,995 ', 'Asia', '73451', '', '', '577'], ['94', 'RÃ©union', '418,585', '', '796 ', '', '415,360', '', '2,429', '10', '461,140', '877', '1,603,660', '1,766,696', '907,717 ', 'Africa', '21,1401', '', '', '2,676'], ['95', 'Oman', '389,758', '', '4,260 ', '', '384,669', '', '829', '2', '72,733', '795', '25,000,000', '4,665,281', '5,358,734 ', 'Asia', '141,2580', '', '', '155'], ['96', 'Bosnia and Herzegovina', '378,083', '', '15,793 ', '', 'N/A', 'N/A', 'N/A', '', '116,649', '4,873', '1,782,014', '549,798', '3,241,214 ', 'Europe', '92052', '', '', '52,472'], ['97', 'Qatar', '372,261', '', '677 ', '', '369,100', '', '2,484', '', '132,581', '241', '3,586,479', '1,277,325', '2,807,805 ', 'Asia', '84,1471', '', '', '885'], ['98', 'Kenya', '326,932', '', '5,651 ', '', '319,519', '', '1,762', '', '5,831', '101', '3,701,693', '66,018', '56,070,618 ', 'Africa', '1729,92215', '', '', '31'], ['99', 'Zambia', '323,058', '', '3,989 ', '', '318,016', '', '1,053', '', '16,667', '206', '3,504,021', '180,775', '19,383,333 ', 'Africa', '604,8596', '', '', '54'], ['100', 'North Macedonia', '312,538', '', '9,316 ', '', '302,807', '', '415', '', '150,027', '4,472', '2,055,472', '986,686', '2,083,208 ', 'Europe', '72241', '', '', '199'], ['101', 'Botswana', '310,431', '', '2,701 ', '', '304,887', '', '2,843', '1', '127,028', '1,105', '2,026,898', '829,402', '2,443,806 ', 'Africa', '89051', '', '', '1,163'], ['102', 'Albania', '276,731', '', '3,497 ', '', '272,893', '', '341', '2', '96,365', '1,218', '1,835,130', '639,040', '2,871,697 ', 'Europe', '108212', '', '', '119'], ['103', 'Algeria', '265,927', '', '6,875 ', '', '178,437', '', '80,615', '6', '5,859', '151', '230,861', '5,086', '45,388,341 ', 'Africa', '1716,602197', '', '', '1,776'], ['104', 'Nigeria', '256,352', '', '3,144 ', '', '250,131', '', '3,077', '11', '1,186', '15', '5,198,572', '24,061', '216,057,474 ', 'Africa', '84368,72142', '', '', '14'], ['105', 'Zimbabwe', '254,098', '', '5,521 ', '', '246,407', '', '2,170', '12', '16,626', '361', '2,359,560', '154,391', '15,282,999 ', 'Africa', '602,7686', '', '', '142'], ['106', 'Luxembourg', '251,873', '', '1,084 ', '', '245,443', '', '5,346', '', '390,047', '1,679', '4,275,297', '6,620,669', '645,750 ', 'Europe', '35960', '', '', '8,279'], ['107', 'Uzbekistan', '239,236', '', '1,637 ', '', '237,406', '', '193', '23', '6,952', '48', '1,377,915', '40,043', '34,410,964 ', 'Asia', '14421,02125', '', '', '6'], ['108', 'Montenegro', '237,901', '', '2,722 ', '', '234,742', '', '437', '6', '378,691', '4,333', '2,484,688', '3,955,124', '628,220 ', 'Europe', '32310', '', '', '696'], ['109', 'Mozambique', '226,463', '', '2,206 ', '', '223,660', '', '597', '13', '6,872', '67', '1,335,253', '40,517', '32,955,178 ', 'Africa', '14614,93925', '', '', '18'], ['110', 'Laos', '210,147', '', '757 ', '', 'N/A', 'N/A', 'N/A', '', '28,092', '101', '1,233,207', '

In [17]:
import csv
file = open('covid_data1.csv','w')
x = csv.writer(file)
for i in final_data:
  x.writerow(i)

In [19]:
import pandas as pd
df = pd.read_csv('covid_data1.csv')
df

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/,1M pop,Unnamed: 15,Population,Continent,1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,1,USA,"87,321,703",NaN,"1,035,847",NaN,"83,159,792",NaN,"3,126,064","2,812",...,"1,039,574,344","3,105,329","334,771,130",North America,43230,NaN,NaN,"9,338",NaN,NaN
1,2,India,"43,232,004",NaN,"524,761",NaN,"42,652,743",NaN,"54,500",698,...,"854,859,461","607,858","1,406,347,202",Asia,"332,6802",NaN,NaN,39,NaN,NaN
2,3,Brazil,"31,456,865",NaN,"668,177",NaN,"30,182,173",NaN,"606,515","8,318",...,"63,776,166","295,955","215,493,041",South America,73233,NaN,NaN,"2,815",NaN,NaN
3,4,France,"29,849,919",NaN,"148,749",NaN,"29,210,587",NaN,"490,583",869,...,"271,490,188","4,141,480","65,553,913",Europe,24410,NaN,NaN,"7,484",NaN,NaN
4,5,Germany,"26,847,783",NaN,"140,183",NaN,"25,882,900",NaN,"824,700",631,...,"122,332,384","1,451,085","84,304,052",Europe,36011,NaN,NaN,"9,782",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,183,Djibouti,"15,686",NaN,189,NaN,"15,427",NaN,70,NaN,...,"305,941","301,154","1,015,895",Africa,"655,3753",NaN,NaN,69,NaN,NaN
183,184,Bermuda,"15,428",NaN,138,NaN,"14,901",NaN,389,NaN,...,"931,509","15,065,404","61,831",North America,44480,NaN,NaN,"6,291",NaN,NaN
184,185,CAR,"14,649",NaN,113,NaN,"6,859",NaN,"7,677",2,...,"81,294","16,282","4,992,797",Africa,"34144,18461",NaN,NaN,"1,538",NaN,NaN
185,186,Dominica,"14,638",NaN,67,NaN,"14,284",NaN,287,NaN,...,"207,131","2,863,575","72,333",North America,"51,0800",NaN,NaN,"3,968",NaN,NaN
186,187,Samoa,"14,187",NaN,28,NaN,"1,605",NaN,"12,554",4,...,"130,226","647,974","200,974",Australia/Oceania,"147,1782",NaN,NaN,"62,466",NaN,NaN

In [27]:
deaths = []
countries = list(df['Country,Other'][0:10])
TotalDeaths = list(df['TotalCases'][0:10])
for i in TotalDeaths:
  v = int(i.replace(',',''))
  deaths.append(v)

[87321703,
 43232004,
 31456865,
 29849919,
 26847783,
 22382352,
 18376587,
 18229288,
 17653375,
 15072747]

In [ ]:
!pip install plotly==5.8.2

In [28]:
import plotly.graph_objects as go

fig = go.Figure([go.Bar(x=countries, y=deaths)])
fig.show()

In [29]:
import plotly.graph_objects as go

fig = go.Figure(data=[go.Pie(labels=countries, values=deaths)])
fig.show()